### ISSUE TITLE
optionCtx.logger is not being used to initialize dbTracer

### ISSUE THREAD

**Issue by sonalys** [amirsalarsafaei/sqlc-pgx-monitoring#8]
on [dbtracer.go:80](https://github.com/amirsalarsafaei/sqlc-pgx-monitoring/blob/master/dbtracer/dbtracer.go#L80C1-L80C36), you always use `slog.Default()`, instead of `optCtx.logger`

WithLogger is not working because of that.

**Comment by amirsalarsafaei** [comment]
@sonalys thanks for your report I fixed it :D  
I'm open to suggestions if you have something else on your mind.
